### ISSUE TITLE
Less.JS helpers (locals)

### ISSUE THREAD

**Issue by ixti** [nodeca/mincer#1]
Styles renderer receives all registered Environment helpers as locals. It would be great to have same with less. Right now problem can be solved with help of EJS:

``` css
/** file: app.less.ejs **/
.btn {
  background: url('<%= asset_path("buttons/dark-bg.png") %>');
}
```
### See Also:
- https://github.com/cloudhead/less.js/issues/798
