### ISSUE TITLE
[Feature Request] Is it possible to add 'preserveHacks' option for CSSWring compressor ?

### ISSUE THREAD

**Issue by tortuetorche** [nodeca/mincer#171]
Because some CSS frameworks, like [Twitter Bootstrap 2.3.2](http://getbootstrap.com/2.3.2/), use star hack selectors:

``` css
.btn-group {
    position: relative;
    display: inline-block;
    *display: inline;
    *zoom: 1;
    *margin-left: .3em
}
```

And without the [`preserveHacks`](https://github.com/hail2u/node-csswring/blob/v2.0.0/README.md#preservehacks) option, CSSWring remove these special selectors.

And if you can add the [`removeAllComments`](https://github.com/hail2u/node-csswring/blob/v2.0.0/README.md#removeallcomments) option too, it'll be really :cool:.
