### ISSUE TITLE
Autoprefixer support

### ISSUE THREAD

**Issue by ai** [nodeca/mincer#95]
Mincer is cool. I plan to use it and will add [Autoprefixer](https://github.com/ai/autoprefixer) support. But Autoprefixer is cool too, maybe it be better to add it to Mincer by default?

It allow you users to forget about vendor prefixes. They will write CSS by latest W3C specs:

``` css
a {
  transition: transform 1s
}
```

and Autoprefixer will add actual prefixes (by Can I Use data) and clean unnecessary prefixes (like `border-radius`):

``` css
a {
  -webkit-transition: -webkit-transform 1s;
  -o-transition: -o-transform 1s;
  transition: -ms-transform 1s;
  transition: transform 1s
}
```

If you agree I will make pull request.
